### PR TITLE
Add support for julia-v0.5 slice->view change

### PR DESCRIPTION
**Pull request by davidavdav**
Julia-v0.5 has renamed `slice` to `view`.  We need this change for dependent packages.

### CODE REVIEW

**Comment by KristofferC** [comment]
Seems like the Apple workers failed to start. I close and reopen to restart.

**Comment by KristofferC** [comment]
Not sure if that worked. If not just force push a rebase.

**Comment by davidavdav** [comment]
I am sorry, I don't quite get your remarks.

**Comment by KristofferC** [comment]
If you force push a rebase commit C.I will run again.

Anyway looks good now. Thanks.

**Pull request merged**
