### PR TITLE
make Minkowski an immutable

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by IainNZ** [comment]
Would anyone be using this field?

**Comment by KristofferC** [comment]
Ref  #26

Imo, this should not be a `type` because it so cheap to just create a new one. Having it as an `immutable` would make vectorization, load hoisting etc possible.

**Comment by IainNZ** [comment]
Yeah it definitely seems like a natural immutable. Just worried about breaking something in user code. I don't really want to take that responsibilty for a package I don't use though... maybe you should take ownership of the package?

**Comment by KristofferC** [comment]
Yeah, it is breaking, that's right. Looking through some more there are a few more "obvious" immutables. 

Not sure what the best course of actions are. If I get collaborator status I could tag a last v0.2 version, do the immutable fixes and bump to v0.3 or something..

**Comment by IainNZ** [comment]
Sounds sensible
@andreasnoack @johnmyleswhite or someone with admin, can you add @KristofferC to collaborators so he can maintain this package?

**Pull request merged**
