### PR TITLE
Remove Metric <: SemiMetric <: PreMetric

### PR DESCRIPTION
**Pull request by matthieugomez**
This PR removes the type structure `Metric, SemiMetric, PreMetric` which makes it harder to define new distance types (solving https://github.com/JuliaStats/Distances.jl/issues/199)

Still, generic distances are encouraged to define `issymmetric` and `issubadditive`, which is used in `pairwise` to accelerate computations.

### CODE REVIEW

**Comment by KristofferC** [comment]
This doesn't look like an improvement to me and doesn't look like standard usage of traits. Traits are typically used for small pieces of extra information that you want to dispatch on (often related to dispatching to an optimized method). This might be the type of indexing (`LinearSlow` or `LinearFast`) or if the length is known (`HasLength`, `IsInfinite` etc). But not to encode big families of types like this.

From #199:

> In StringDistances, I would love to be able to define certain functions on these groups. This is not possible, however, due to the lack of multiple inheritance in Julia.

This feels like something that is more suitable for using traits for (which there should be no problem for you to do) so I don't really see that as an argument for this.

Also, remember this package is very old and has a large number of packages depending on it. Breaking changes should be kept to an absolute minimum.

**Comment by matthieugomez** [comment]
Right it’s not even a trait. It ended up being simpler to define two
functions. I could not think of an example where one would need to dispatch
on premetric vs metric in a hot loop.

For StringDistances, traits won’t work since I would like to define
specialized methods for findall etc, which is not possible using traits.

I do get the argument about breaking changes, but the change is mainly
going to impact developers, rather than end users.

**Comment by matthieugomez** [comment]
Another example is the following. Suppose I define a parametric type that corresponds to the normalized version of a distance (say, always between 0 and 1).
```
struct Normalized{T <: PreMetric}
   dist::T
```
There is currently no way to express that `Normalized(dist)` would by symmetric if `dist` is symmetric. With this PR, one could write
```
issymmetric(dist::Normalized) = issymmetric(dist.dist)
```

**Comment by matthieugomez** [comment]
To me, the current situation of `Distances.jl` feels a little bit the same as if Base defined something like 
```julia
  abstract type SymmetricAbstractArray <: AbstractArray end
```
This would make it impossible create new array types (e.g. TriangularArray or SparseArray) that may end up being symmetric. 

- This exact problem is encountered within this package. At [some point](https://github.com/JuliaStats/Distances.jl/blob/a43d76b23874c10d8ab44909f7d4816ba88ef7db/src/metrics.jl#L200 ), the package tries to define a special distance type,  `UnionMetrics`. However, because of the forced inheritance `Metric <: SemiMetric <: PreMetric`, the package has to do the following workaround
   ```julia
   abstract type UnionPreMetric <: PreMetric
   abstract type UnionSemiMetric <: SemiMetric
   abstract type UnionMetric <: Metric
   const UnionMetrics = Union{UnionPreMetric, UnionSemiMetric, UnionMetric}
   ```
   This is inelegant, and also create some weird stuff --- in particular we don't have `UnionMetric <: UnionPreMetric`.

- This workaround does not always work. Suppose I define a parametric type that corresponds to the normalized version of a distance (say, always between 0 and 1).
  ```julia
  struct Normalized{T <: PreMetric} <: PreMetric
     dist::T
  end
   ```
   There is currently no way to express that `Normalized(dist)` remains symmetric if `dist` is symmetric. This is a big problem if I want to pass a normalized distance to a method that is only defined on `SemiMetric`s. In contrast, with this PR, one could simply write
  ```julia
  issymmetric(dist::Normalized) = issymmetric(dist.dist)
  ```

**Pull request closed without merging**
