### PR TITLE
Extend Mahalanobis tests

### PR DESCRIPTION
**Pull request by dkarrasch**

### CODE REVIEW

**Comment by juliohm** [comment]
It would be nice to address the use case with static arrays as well as pointed out by @nalimilan

**Comment by dkarrasch** [comment]
Well, that requires us to include a new test dependency. If you want, the `Hermitian(Q)` plays the role of a static matrix, because it's an `AbstractMatrix`, not a `Matrix` anymore. You couldn't construct `Mahalanobis(Hermitian(Q))` before v0.10.

**Comment by juliohm** [comment]
Got it. It makes sense to test with other matrix types that don't add dependencies to the test suite.

**Review by nalimilan — APPROVED** [review]
Thanks!

How hard would it be to test an array with a non-`Real` eltype while you're at it?

**Comment by dkarrasch** [comment]
Is `ComplexF64` non-`Real` enough? 😉

**Pull request merged**
