### PR TITLE
WIP: Nonallocating API for distances between matrix columns

### PR DESCRIPTION
**Pull request by chethega**
This is a proposal for what to do with [https://github.com/JuliaStats/Distances.jl/issues/83](https://github.com/JuliaStats/Distances.jl/issues/83).

I went ahead and added an allocation-free API for metrics.jl. I also added colwise and pairwise versions that use the new API, to see how bad it is.

The pairwise with hilbert-curve memory access pattern ended up quite lengthy, but the general divide-and-conquer gives a good speed-up.

This is WIP -- one would need to think about how to improve the API for e.g. weighted metrics, so please test & comment but don't put it into master without massive edits.

### CODE REVIEW

**Comment by chethega** [comment]
Some performance tests:


```
m = 1000;n=4; res=zeros(Float64, m); A = rand(n, m); B = rand(n, m); d = Cityblock();
       colwise!(res,d,A,B);
       @time colwise!(res,d,A,B);
       colwise_noalloc!(res,d,A,B);
       @time colwise_noalloc!(res,d,A,B);
  0.000048 seconds (2.00 k allocations: 93.906 KiB)
  0.000010 seconds (4 allocations: 160 bytes)
```
```
m = 10000;n=8; res=zeros(Float64, m); A = rand(n, m); B = rand(n, m); d = Cityblock();
       colwise!(res,d,A,B);
       @time colwise!(res,d,A,B);
       colwise_noalloc!(res,d,A,B);
       @time colwise_noalloc!(res,d,A,B);
  0.001908 seconds (20.00 k allocations: 937.656 KiB)
  0.000408 seconds (4 allocations: 160 bytes)
```
And for pairwise:

```
m = 1000;n=4; res=zeros(Float64, m,m); A = rand(n, m); B = rand(n, m); d = Cityblock();
       pairwise!(res,d,A,B);
       @time pairwise!(res,d,A,B);
       pairwise_noalloc!(res,d,A,B);
       @time pairwise_noalloc!(res,d,A,B);

       pairwise_advanced!(res,d,A,B,false,false,false);
       @time pairwise_advanced!(res,d,A,B,false,false,true);

       pairwise_advanced!(res,d,A,B,true,false,false);
       @time pairwise_advanced!(res,d,A,B,true,false,true);

  0.041402 seconds (1.00 M allocations: 45.822 MiB, 4.41% gc time)
  0.009580 seconds (4 allocations: 160 bytes)
cache_thresh: 312
single threaded, using naive order:
  0.009158 seconds (21 allocations: 704 bytes)
cache_thresh: 312
using hilbert: false, split into 2 packages for 2 threads:
...

  0.036725 seconds (1.00 M allocations: 45.822 MiB, 7.28% gc time)
  0.008688 seconds (4 allocations: 160 bytes)
  0.014427 seconds (315 allocations: 10.828 KiB)

```
And for larger matrices:

```
m = 10000;n=8; res=zeros(Float64, m,m); A = rand(n, m); B = rand(n, m); d = Cityblock();
....

3.291277 seconds (100.01 M allocations: 4.471 GiB, 5.56% gc time)
1.364368 seconds (4 allocations: 160 bytes)
cache_thresh: 156
single threaded, using naive order:
  1.340553 seconds (21 allocations: 704 bytes)
cache_thresh: 156
using hilbert: false, split into 2 packages for 2 threads:
  0.702424 seconds (318 allocations: 10.563 KiB)
```

And for even larger matrices:
```
m = 20000;n=8; res=zeros(Float64, m,m); A = rand(n, m); B = rand(n, m); d = Cityblock();
...
 13.099807 seconds (400.02 M allocations: 17.882 GiB, 5.09% gc time)
 17.865832 seconds (4 allocations: 160 bytes)
  5.359074 seconds (21 allocations: 704 bytes)
  2.962303 seconds (318 allocations: 10.938 KiB)

```
I must confess that I don't understand why pairwise! outperforms pairwise_noalloc! in some cases. Also, adding more threads tends not to help too much. 

I have not shown timings for the hilbert-curve memory layout, since it appears not to help too much and is slightly buggy.

**Comment by KristofferC** [comment]
Would it be possible to separate this PR into two. One which just fixes https://github.com/JuliaStats/Distances.jl/issues/83 and one that deals with the tiling for better cache usage.

**Comment by chethega** [comment]
Sure, will do. I am quite happy with the unsafe_view, and just chose the bad API because I did not know whether you would be happy with pointer games.

**Comment by chethega** [comment]
I guess we can close this. Your version with unsafe_views is as performant as this, and the recursive subdivision traversal appears to be no better than the direct order. For anyone who wants to look at the hilbert-curve order, see [https://gist.github.com/chethega/00241c6312d3fe28afc5532708a69b3d](https://gist.github.com/chethega/00241c6312d3fe28afc5532708a69b3d).

**Pull request closed without merging**
